

book:
  author: SSH
  name: Spring Boot
author:
  name: SSH
  age: 18

server:
  port: 8888
# 用户会话session 过期时间，以秒为单位
#  session-timeout: 10
# 默认访问路径
#  context-path: /
  tomcat:
    context-path: /
    uri-encoding: UTF-8
#  ssl:
#    key-store: .keystore
#    key-password: springboot
#    key-store-type: JKS
#    key-alias: tomcat


logging:
  file: D:/tmp/log/spring-boot/spring-boot-log.log
  level:
    org:
      springframework:
        web: DEBUG

# 自动装配

hello:
  msg: shenshauihu

#debug: true


#spring:
#  mvc:
#    favicon:
#      enabled: true
spring:
  mvc:
    static-path-pattern: /static/**

  datasource:
    url: jdbc:oracle:thin:@47.102.111.109:16021:xe
    username: boot
    password: boot
    driver-class-name: oracle.jdbc.driver.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    rest:
      base-path: /api

    mongodb:
      host: 47.102.111.109
      port: 17012
      uri: mongodb://47.102.111.109:17012/test

  redis:
    host: 127.0.0.1
    port: 6379
    database: 5

  thymeleaf:
    cache: false

  batch:
    # 开启初始化数据库
    initialize-schema: always
    # 关闭自动执行
    job:
      enabled: false

#  activemq:
#    broker-url: tcp://47.102.111.109:16018

  rabbitmq:
    host: 47.102.111.109
    port: 16172

# shell

shell:
  auth:
    simple:
      user:
        name: ssh
        password: ssh