

book:
  author: SSH
  name: Spring Boot
author:
  name: SSH
  age: 18

server:
  port: 8888
# 用户会话session 过期时间，以秒为单位
#  session-timeout: 10
# 默认访问路径
#  context-path: /
#  tomcat:
#    context-path: /
#    uri-encoding: UTF-8
#  ssl:
#    key-store: .keystore
#    key-password: springboot
#    key-store-type: JKS
#    key-alias: tomcat


logging:
  file: D:/tmp/log/spring-boot-log.log
  level:
    org:
      springframework:
        web: DEBUG

# 自动装配

hello:
  msg: shenshauihu

debug: true


#spring:
#  mvc:
#    favicon:
#      enabled: true
spring:
  mvc:
    static-path-pattern: /static/**
